spring:
  datasource:
    username: root
    password: 1234
    url: jdbc:mysql://localhost:3306/student?characterEncoding=UTF8&autoReconnect=true&useSSL=true
    driver-class-name: com.mysql.cj.jdbc.Driver
  #整合mybatis